# Generated by Django 4.2.2 on 2023-08-03 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.FileField(default='default', upload_to='recipe', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
