"""Содержит константы приложения recipes."""
MAX_TAG_NAME_LENGTH = 150
TAG_COLOR_CODE_LENGTH = 7
TAG_COLOR_CODE_REGEXP = r'\A#[0-9a-fA-F]{6}\Z'
MAX_INGREDIENT_NAME_LENGTH = 150
MAX_INGREDIENT_MEASUREMENT_UNIT_LENGTH = 20
MAX_RECIPE_NAME_LENGTH = 200
RECIPES_ORDERING = ['id']  # ('-pub_date',)  #
