# Generated by Django 4.2.2 on 2023-08-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_recipe_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(db_table='ShoppingCart', related_name='in_shopping_cart', to='api.recipe', verbose_name='Список покупок'),
        ),
    ]
