# Generated by Django 4.2.2 on 2023-08-20 07:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_recipe_pub_date_alter_recipe_image'),
        ('users', '0002_user_shopping_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='in_favore', to='api.recipe', verbose_name='Избранные рецепты'),
        ),
        migrations.AlterField(
            model_name='user',
            name='shopping_cart',
            field=models.ManyToManyField(blank=True, db_table='ShoppingCart', related_name='in_shopping_cart', to='api.recipe', verbose_name='Список покупок'),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_to',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
    ]
